Repository gardener/gardener-extension-shoot-networking-filter, pull requests merged in 2022-05, with the labels that each got.

#9 Update to new egress-filter images with updated base images
  charts/images.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#12 Add pod security policy
  hack/api-reference/config.md
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/controller/lifecycle/actuator.go
Labels: kind/api-change, needs/ok-to-test, needs/second-opinion, size/m

#13 Update Alpine Linux to v3.15.4
  Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
