Repository gardener/gardener-extension-shoot-networking-filter, pull requests merged in 2022-07, with the labels that each got.

#19 Change base image from alpine to distroless
  Dockerfile
Labels: area/open-source, area/security, kind/enhancement, reviewed/lgtm, needs/ok-to-test, size/xs

#22 Adapt the priority according to the gardener guideline
  charts/gardener-extension-shoot-networking-filter/templates/deployment.yaml
  charts/gardener-extension-shoot-networking-filter/templates/priorityclass.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#23 Cleanup makefile
  .golangci.yaml
  .test-defs/lifecycle.yaml
  Makefile
  go.mod
  go.sum
  hack/check-docforge.sh
  test/system/lifecycle/lifecycle_test.go
  vendor/k8s.io/helm/internal/third_party/dep/fs/fs.go
  vendor/k8s.io/helm/internal/third_party/dep/fs/rename.go
  vendor/k8s.io/helm/internal/third_party/dep/fs/rename_windows.go
  vendor/k8s.io/helm/pkg/chartutil/capabilities.go
  vendor/k8s.io/helm/pkg/chartutil/capabilities_versions_generated.go
  vendor/k8s.io/helm/pkg/chartutil/create.go
  vendor/k8s.io/helm/pkg/chartutil/doc.go
  vendor/k8s.io/helm/pkg/chartutil/load.go
  vendor/k8s.io/helm/pkg/chartutil/requirements.go
  vendor/k8s.io/helm/pkg/chartutil/values.go
  vendor/k8s.io/helm/pkg/downloader/chart_downloader.go
  vendor/k8s.io/helm/pkg/downloader/manager.go
  vendor/k8s.io/helm/pkg/engine/engine.go
  vendor/k8s.io/helm/pkg/getter/getter.go
  vendor/k8s.io/helm/pkg/getter/httpgetter.go
  vendor/k8s.io/helm/pkg/getter/plugingetter.go
  vendor/k8s.io/helm/pkg/helm/environment/environment.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/chart.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/config.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/metadata.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/template.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/hook.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/info.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/release.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/status.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/test_run.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/release/test_suite.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/version/version.pb.go
  vendor/k8s.io/helm/pkg/provenance/sign.go
  vendor/k8s.io/helm/pkg/repo/chartrepo.go
  vendor/k8s.io/helm/pkg/repo/index.go
  vendor/k8s.io/helm/pkg/repo/repo.go
  vendor/k8s.io/helm/pkg/resolver/resolver.go
  vendor/k8s.io/helm/pkg/sympath/walk.go
  vendor/k8s.io/helm/pkg/tlsutil/cfg.go
  vendor/k8s.io/helm/pkg/version/version.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/second-opinion, size/xl
