Repository gardener/gardener-extension-shoot-networking-filter, pull requests merged in 2023-07, with the labels that each got.

#72 Introduce persona-based docs
  .docforge/manifest.yaml
  docs/operations/deployment.md
Labels: kind/cleanup, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#74 Add dependabot to manage gardener packages
  .github/dependabot.yaml
  .github/workflows/vendor_gardener.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#77 Bump github.com/gardener/gardener from 1.75.1 to 1.76.0
  .github/workflows/vendor_gardener.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/etcd-druid/api/v1alpha1/types_etcd.go
  vendor/github.com/gardener/gardener/hack/generate-monitoring-docs.sh
  vendor/github.com/gardener/gardener/hack/test-prometheus.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_operatingsystemconfig.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/operator/v1alpha1/constants.go
  vendor/github.com/gardener/gardener/pkg/apis/operator/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/tls_cipher_suites.go
  vendor/github.com/gardener/gardener/pkg/utils/managedresources/managedresources.go
  vendor/github.com/gardener/gardener/pkg/utils/miscellaneous.go
  vendor/modules.txt
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m
