Repository gardener/gardener-extension-shoot-networking-filter, pull requests merged in 2023-06, with the labels that each got.

#69 Fixed broken links - 2023.06
  README.md
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/xs

#64 Adapt to golang egress-filter image.
  Makefile
  charts/gardener-extension-shoot-networking-filter/values.yaml
  charts/images.yaml
  example/controller-registration.yaml
  go.mod
  go.sum
  hack/api-reference/config.md
  hack/test-e2e-provider-local.sh
  hack/tools.go
  hack/tools/bin/.gitkeep
  pkg/apis/config/types.go
  pkg/apis/config/v1alpha1/types.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/lifecycle/actuator.go
  test/e2e/common_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/network_test.go
  test/templates/network-test.yaml.tpl
  test/templates/templates.go
  vendor/modules.txt
Labels: kind/api-change, needs/ok-to-test, needs/second-opinion, size/xl

#70 Update golang to 1.20.5
  Dockerfile
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#63 Add providerConfig to example configuration in usage document.
  docs/usage/shoot-networking-filter.md
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
