Repository gardener/gardener-extension-shoot-networking-filter, pull requests merged in 2023-01, with the labels that each got.

#46 Drop support for kubernetes < 1.20 for shoot networking filter extension
  example/10-fake-shoot-controlplane.yaml
  example/30-cluster.yaml
  go.mod
  hack/api-reference/config.json
  hack/api-reference/config.md
  pkg/controller/lifecycle/actuator.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#47 Update builder image to golang:1.19.5
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/ok-to-test

#48 Add CVE categorisation.
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
