Repository gardener/gardener-extension-shoot-networking-filter, pull requests merged in 2024-07, with the labels that each got.

#154 add imagevector-labels for oci-images
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#160 Reduce `egress-filter-applier` resource requests
  pkg/controller/lifecycle/actuator.go
Labels: kind/enhancement, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#163 Publish Helm charts as OCI artifacts
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, needs/review, size/s, ok-to-test
