Repository gardener/gardener-extension-shoot-networking-filter, pull requests merged in 2024-02, with the labels that each got.

#118 Add possibility to deploy to clusters that are not gardener shoots.
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  charts/gardener-extension-shoot-networking-filter/templates/deployment.yaml
  charts/gardener-runtime-networking-filter/Chart.yaml
  charts/gardener-runtime-networking-filter/templates/config.yaml
  charts/gardener-runtime-networking-filter/templates/deployment.yaml
  charts/gardener-runtime-networking-filter/templates/rbac.yaml
  charts/gardener-runtime-networking-filter/templates/secret-oauth2.yaml
  charts/gardener-runtime-networking-filter/templates/serviceaccount.yaml
  charts/gardener-runtime-networking-filter/values.yaml
  cmd/gardener-runtime-networking-filter/main.go
  example/controller-registration.yaml
  pkg/cmd/options.go
  pkg/constants/constants.go
  pkg/controller/lifecycle/actuator.go
  pkg/controller/lifecycle/filterlistprovider.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xl

#121 Change default for pspEnabled.
  VERSION
  cmd/gardener-runtime-networking-filter/main.go
  example/controller-registration.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#123 Make repo compliant
  .reuse/dep5
  CONTRIBUTING.md
  LICENSE
  LICENSES/Apache-2.0.txt
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/ISC.txt
  LICENSES/LicenseRef-PUBLIC-DOMAIN-xi2-xy.txt
  LICENSES/MIT.txt
  LICENSES/MPL-2.0.txt
  README.md
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xl, area/ipcei
