Repository gardener/gardener-extension-shoot-networking-filter, pull requests merged in 2025-04, with the labels that each got.

#222 Address TODO for legacy NetworkPolicy labels
  charts/gardener-extension-shoot-networking-filter/templates/service.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#223 Remove RBAC wildcard references from Roles
  charts/gardener-extension-shoot-networking-filter/templates/rbac.yaml
  charts/gardener-runtime-networking-filter/templates/rbac.yaml
  example/25-rbac.yaml
  example/controller-registration.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#225 Update base image to `debian12`
  Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#227 remove unneeded `deletecollection`
  charts/gardener-extension-shoot-networking-filter/templates/rbac.yaml
  charts/gardener-runtime-networking-filter/templates/rbac.yaml
  example/controller-registration.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#229 Allow `patch` of the `gardener-extension-heartbeat` lease
  charts/gardener-extension-shoot-networking-filter/templates/rbac.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, ok-to-test
